### ISSUE TITLE
Extension causes unexpected termination of extension host

### ISSUE THREAD

**Issue by rhys-vdw** [karuna/haml-vscode#11]
![image](https://user-images.githubusercontent.com/822105/44186870-3f412880-a15f-11e8-998e-fc3e666ded24.png)

Just narrowed down the cause to this extension. This is what I see in VSCode console:

![image](https://user-images.githubusercontent.com/822105/44186867-35b7c080-a15f-11e8-9b1a-55c5c2426374.png)

I'm assuming this has been caused by update to VSCode 1.26.0

**Comment by karuna** [comment]
@rhys-vdw I think this is important, I will check this tonight.

**Comment by karuna** [comment]
@rhys-vdw I think it's just your installation, it's fine with me here.

**Comment by rhys-vdw** [comment]
Ah, interesting. I will try it again tomorrow at work.

**Comment by karuna** [comment]
@rhys-vdw can you update your visual studio code to 1.26.1 and try again?
I think this is the cause of the problem: https://github.com/Microsoft/vscode/issues/56387

**Comment by rhys-vdw** [comment]
It's all good. I deleted and reinstalled the package and it's fixed in 1.26.0

**Comment by rhys-vdw** [comment]
Oops, I told a lie. It did work at first but then stopped. I've updated now and so far so good. 👍
