### ISSUE TITLE
No syntax highlighting within `:coffeescript` tags

### ISSUE THREAD

**Issue by kjleitz** [karuna/haml-vscode#7]
Syntax highlighting works within `:javascript` tags, but not within `:coffeescript` tags. Check it out:

![screen shot 2018-01-10 at 11 30 54 am](https://user-images.githubusercontent.com/18669659/34783656-20465704-f5fa-11e7-95a9-e3cd9b4cfe3e.png)

Highlighting does work in `.coffee` files, but not within a `:coffeescript` tag in a `.haml` file.

Great work, by the way :) Don't know what I'd do without this extension!

**Comment by karuna** [comment]
@kjleitz I've pushed verson 1.1.0. Let me know if it doesn't work.

**Comment by kjleitz** [comment]
Works great! Thanks for the quick response, man!
