### ISSUE TITLE
Major slowdown with recent VS Code Update

### ISSUE THREAD

**Issue by ndelage** [karuna/haml-vscode#8]
This might be a shot in the dark, but after a recent (Feb 1st 2018) VS Code update (I'm now running `Version 1.19.3 (1.19.3)`), enabling the Better HAML extension causes a terrible slowdown during editing. I'm seeing crazy latency when typing (> 1 second per character). It's made this extension impossible to use.

Strangely, I experience the slowdown **only when editing non-haml files** (e.g. `.rb`). I don't experience the slowdown when editing HAML files.

Enabling/disabling the extension also fixes/causes the slowdown I'm experiences. So maybe it's a dependency of Better HAML that's to blame? I figured I'd start here though.

**Comment by ndelage** [comment]
I ended up switching to "Ruby HAML" (vscode-haml-ruby) which is working just fine.

**Comment by karuna** [comment]
I don't get the slowdown, I've been using vscode to 1.19.3 since it come out and never got any problem.

**Comment by ndelage** [comment]
I wonder what's different on my system. If there's anything I can do to debug this I'm more than willing.

**Comment by karuna** [comment]
@ndelage Help -> Toggle Developer Tools -> Console tab

is there something weird? usually the error is shown in red.
